apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-messaging-blue
  template:
    metadata:
      labels:
        app: django-messaging-blue
    spec:
      containers:
      - name: django-messaging
        image: your-dockerhub-username/django-messaging:1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-blue-service
spec:
  selector:
    app: django-messaging-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
